export const PROMPT_TEMPLATES = {
  image: [
    { name: "Business", prompt: "Professional corporate business scene in modern office" },
    { name: "Technology", prompt: "Futuristic technology and digital innovation concept" },
    { name: "Healthcare", prompt: "Medical healthcare professional in clinical setting" },
    { name: "Education", prompt: "Learning and education environment with study materials" },
    { name: "Real Estate", prompt: "Luxury modern interior design and architecture" },
    { name: "Food", prompt: "Gourmet food photography with elegant styled plating" },
    { name: "Nature", prompt: "Stunning natural landscape with dramatic lighting" },
    { name: "Wellness", prompt: "Peaceful wellness and self-care lifestyle scene" },
    { name: "Finance", prompt: "Financial growth and investment concept visualization" },
    { name: "Travel", prompt: "Breathtaking travel destination with cultural elements" },
    { name: "Remote Work", prompt: "Modern remote work home office setup with laptop" },
    { name: "Abstract", prompt: "Vibrant abstract background with flowing geometric shapes" },
  ],
  vector: [
    { name: "Business", prompt: "Professional corporate business infographic illustration" },
    { name: "Medical", prompt: "Healthcare and medical science vector illustration" },
    { name: "Technology", prompt: "Digital technology and data visualization icons" },
    { name: "Education", prompt: "Educational learning concept illustration for school" },
    { name: "Social Media", prompt: "Trendy social media marketing design elements" },
    { name: "Icon Set", prompt: "Clean flat design icon set for mobile application" },
    { name: "Pattern", prompt: "Seamless repeating decorative pattern design" },
    { name: "Isometric", prompt: "Isometric 3D illustration of modern workspace" },
    { name: "Character", prompt: "Diverse cartoon character illustration set" },
    { name: "Logo", prompt: "Modern minimalist geometric logo design concepts" },
  ],
  video: [
    { name: "Product Demo", prompt: "Smooth cinematic product reveal with rotating camera" },
    { name: "Corporate", prompt: "Professional corporate brand video with modern office" },
    { name: "Nature", prompt: "Stunning slow motion nature footage with ambient light" },
    { name: "Aerial", prompt: "Sweeping drone aerial footage over scenic landscape" },
    { name: "Timelapse", prompt: "Urban cityscape timelapse from golden hour to night" },
    { name: "Action", prompt: "Dynamic action sequence with fast tracking camera" },
  ],
};
